parameters:
#    mc_module.example.class: Mc\ModuleBundle\Example
    router.helper.class: Mc\McService\RouterService\RouterHelper

services:
#    mc_module.example:
#        class: %mc_module.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    router.helper:
        class: %router.helper.class%
