parameters:
#    mc_module.example.class: Mc\ModuleBundle\Example

services:
#    mc_module.example:
#        class: %mc_module.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
