mc_college_homepage:
    pattern: /
    defaults: { _controller: McCollegeBundle:Portal:index }
    
mc_college_program:
    pattern: /program/{id}
    defaults: { _controller: McCollegeBundle:Program:index }
    requirements:
        id: \d+

mc_college_learn:
    pattern:  /learn/{id}
    defaults: { _controller: McCollegeBundle:Default:index , id : 0 }
    requirements:
        id: \d+
