parameters:
#    mc_college.example.class: Mc\CollegeBundle\Example

services:
#    mc_college.example:
#        class: %mc_college.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
