parameters:
#    mc_admin.example.class: Mc\AdminBundle\Example

services:
#    mc_admin.example:
#        class: %mc_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
