parameters:
#    mc_admin.example.class: Mc\AdminBundle\Example


services:
#    mc_admin.example:
#        class: %mc_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    mc_user.registration.form.type:
        class: Mc\AdminBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tag:
            - { name: form.type, alias: mc_user_registration }