parameters:

services:
    mc_user.registration.form.type:
        class: Mc\AdminBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: mc_user_registration }

    mc_user.profile.form.type:
        class: Mc\AdminBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: mc_user_profile }